#!/bin/sh
ruby script/update_version_file.rb
ruby script/create_const_data.rb
cd ../server
ruby script/backup_db.rb
ruby script/create_font_swf.rb
cd ../client
ruby script/dae_converter.rb
/usr/lib/flex3/bin/mxmlc ./src/Unlight.mxml
sudo cp ./src/Unlight.swf /home/www/
sudo cp -rf ./public /home/www/
find /home/www/public -regex ".*svn.*"|xargs sudo rm -rf
# cd ../server/bin
# sudo ./authserver restart
# sudo ./lobbyserver restart
# sudo ./chatserver restart
# sudo ./gameserver restart
